CRM/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    
]

Chaurasia_brothers/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('display_app.urls')),
    path('crm', include('CRM.urls')),
    path('im', include('Inventory_managment.urls')),
    path('acc/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

Inventory_managment/urls.py
from django.contrib import admin
from django.urls import path
from Inventory_managment import views



urlpatterns = [
    path("", views.index, name='home'),
    path("about", views.about, name='about'),
    path("partners", views.partners, name='partners'),
    path("contacts", views.contacts, name='contacts'),
    path("products", views.products, name='products'),
    path("productdetails", views.productdetails, name='productdetails'),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    
]

display_app/urls.py
from django.contrib import admin
from django.urls import path
from display_app import views


urlpatterns = [
    path("", views.products, name='home'),
]

CRM/models.py
from django.db import models
from django.db.models.enums import Choices

# Create your models here.

class customers(models.Model):
    firstName= models.CharField(max_length=25, null=True, blank=True)
    lastName= models.CharField(max_length=25, null=True, blank=True)
    Company = models.CharField(max_length=50, default='General')
    contact_no= models.CharField(max_length=10)
    email= models.EmailField()

    def __str__(self):
        return self.firstName+' '+ self.lastName
    

ADDRESS_TYPE =(
    ('home', 'home'),
    ('office', 'office'),
    ('billing', 'billing'),
    ('shipping', 'shipping')
)

class addresses(models.Model):
    customer = models.ForeignKey(customers, on_delete= models.CASCADE)
    address_type = models.CharField(choices= ADDRESS_TYPE, max_length=10, default= 'home')
    firstLine= models.CharField(max_length=50)
    secondline = models.CharField(max_length=50, null= True, blank=True)
    Block = models.CharField(max_length=25)
    District = models.CharField(max_length=25)
    State = models.CharField(max_length=25)
    pin = models.IntegerField()

TRANSACTION_TYPE =(
   ('SALES','SALES'),
   ('PURCHASE','PURCHASE'),
   ('PAYMENT IN', 'PAYMENT IN'),
   ('PAYMENT OUT', 'PAYMENT OUT'),
   ('SALE RETURN', 'SALE RETURN'),
   ('PURCHASE RETURN', 'PURCHASE RETURN')
)
class transactions(models.Model):
    transactionType= models.CharField(choices= TRANSACTION_TYPE, max_length= 19, default= 'Sales')

Inventory_managment/models.py
from django.db import models
from display_app.models import Products
from CRM.models import customers 


# Create your models here.

Availablity_CHOICES = (
    ('Available', 'Available'),
    ('Below Reorder level', 'Below_Reorder_level'),
    ('Out of Stock', 'Out_of_Stock')
)




class Inventory(models.Model):
    Product = models.ForeignKey(Products, on_delete=models.PROTECT)
    available_qty = models.IntegerField(default='0')
    Availablity_status = models.CharField(choices=Availablity_CHOICES, max_length=19, default='Out of Stock')
    reorder_level = models.PositiveSmallIntegerField(default='2')
    target_level = models.PositiveIntegerField(default='10')

    def __str__(self):
        return self.Product
    
    def shelve_status(self):
        if self.available_qty == 0:
            if 0 < self.available_qty > self.reorder_level:
                return "Item to be Ordred."
            return "Item is out of stock."
        else:
            return "Item is available on the shelves."



class Sales_Orders(models.Model):
    customer = models.ForeignKey(customers, on_delete=models.PROTECT)
    total_value = models.DecimalField(max_digits=7, decimal_places=2)
    total_tax = models.DecimalField(max_digits=5, decimal_places=2)
    total_amount= models.DecimalField(max_digits=7, decimal_places=2)


class Sales_Orders_Details(models.Model):
    Sales_Order = models.ForeignKey(Sales_Orders, on_delete=models.PROTECT)
    Product = models.ForeignKey(Products, on_delete=models.PROTECT)
    qty = models.PositiveIntegerField(default='0')
    total_value = models.PositiveIntegerField()
    tax = models.PositiveSmallIntegerField()
    amount = models.PositiveIntegerField()

accounts/models.py
from django.db import models

# Create your models here.
class cashIn(models.Model): 
    cash = models.CharField(max_length=10)

display_app/models.py
from django.db import models


# Create your models here.

TAX_CHOICES =(
    ('0%', '0%'),
    ('5%', '5%'),
    ('12%', '12%'),
    ('18%', '18%'),
    ('28%', '28%')
)


class section(models.Model):
    section = models.CharField(max_length=25, default='No section assigned')

    def __str__(self):
        return self.section

class brand(models.Model):
    brand = models.CharField(max_length=25, default= 'Not Filled')

    def __str__(self):
        return self.brand


class Products(models.Model):
    Item = models.CharField(max_length=25)
    Discription = models.CharField(max_length=225, blank=True, null=True)
    section = models.ForeignKey(section, on_delete=models.PROTECT)
    Brand = models.ForeignKey(brand, on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    Tax_slab = models.CharField(choices=TAX_CHOICES, max_length=12, default='0%')

    def __str__(self):
        return self.Item


class upcoming_products(models.Model):
    Products= models.ForeignKey(Products, on_delete=models.PROTECT)
    demand= models.IntegerField()

procurment/models.py
from django.db import models
from django.db.models.deletion import PROTECT
from django.db.models.fields import CharField

# Create your models here.
class suppliers(models.Model):
    company=models.CharField(max_length=50)
    contactPerson=models.CharField(max_length=50)
    contact_no1= models.CharField(max_length=10)
    email= models.EmailField()

ADDRESS_TYPE =(
    ('home', 'home'),
    ('office', 'office'),
    ('billing', 'billing'),
    ('shipping', 'shipping')
)

class addresses(models.Model):
    customer = models.ForeignKey(suppliers, on_delete= models.CASCADE)
    address_type = models.CharField(choices= ADDRESS_TYPE, max_length=10, default= 'home')
    firstLine= models.CharField(max_length=50)
    secondline = models.CharField(max_length=50, null= True, blank=True)
    Block = models.CharField(max_length=25)
    District = models.CharField(max_length=25)
    State = models.CharField(max_length=25)
    pin = models.IntegerField()


class purchaseOrders(models.Model):
    party = models.ForeignKey(suppliers, on_delete=PROTECT)
    

Inventory_managment/views.py
from django.shortcuts import render
from .models import Products
from django.views.generic import ListView, DetailView, View

# Create your views here.
def index(request):
    return render(request,'index.html',)

def about(request):
    return render(request,'about.html')

def partners(request):
    return render(request,'partners.html')

def contacts(request):
    return render(request,'contacts.html')

def productdetails(request):
    context = {
        'product' : Products.objects.all()
    }
    return render(request,'productdetails.html', context)

class ProductList(ListView):
    model = Products
    paginate_by = 4
    template_name = "Products.html"
   
def products(request):
    context = {
            'product' : Products.objects.all()
         }
    return render(request,'productdetails.html', context)

class ProductDetailView(DetailView):
    model = Products
    template_name = "product.html"

accounts/views.py
from django.shortcuts import render

# Create your views here.


def is_valid_form(values):
    valid = True
    for field in values:
        if field == '':
            valid = False
    return valid

display_app/views.py
from django.shortcuts import render
from .models import Products

# Create your views here.
def products(request):
    context = {
        'Products': Products.objects.all()
    }
    return render(request,'disProducts.html',context)

procurment/views.py
from django.shortcuts import render

# Create your views here.

Inventory_managment/templates/Productdetails.html
{% extends 'base.html' %}

{% block title %}{{ Products.Item }}
{% endblock title %}

{% block body1 %}

<main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_section_display }}</span>
              </a>
            </div>

            <p class="lead">
             
              <span>${{ object.price }}</span>
              
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.Discription }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
    {% endblock body1 %}
        
             {% block body2 %}
             {% endblock body2 %} 

Inventory_managment/templates/about.html
{% extends 'base.html' %}

{% block title %}About Us{% endblock title %}

{% block body1 %}

    {% endblock body1 %}
        
             {% block body2 %}
             {% endblock body2 %} 

Inventory_managment/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %} || ISC</title>
  <!-- <link rel="stylesheet" href="../static/css/bootstrap.min.css"> -->
  
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css"></style>
</head>

<body data-new-gr-c-s-check-loaded="14.1014.0" data-gr-ext-installed>





  
  <style>@media (min-width: 800px) and (max-width: 850px) {
    .navbar:not(.top-nav-collapse) {
        background: #1C2331!important;
    }
}

.carousel,.carousel .carousel-inner,.carousel .carousel-inner .active,.carousel .carousel-inner .carousel-item,.view,body,html{height:100%}.navbar{background-color:rgba(0,0,0,.2)}.page-footer,.top-nav-collapse{background-color:#1C2331}@media only screen and (max-width:768px){.navbar{background-color:#1C2331}}
</style>

<nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand" href="" target="_blank">
      <strong>ISC</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link waves-effect waves-light" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light" href="#" target="_blank">About ISC</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light" href="#" target="_blank">Free
            download</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light" href="#" target="_blank">Free tutorials</a>
        </li>
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        <li class="nav-item">
          <a href="#" class="nav-link waves-effect waves-light" target="_blank">
            <i class="fab fa-facebook-f"></i>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link waves-effect waves-light" target="_blank">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link border border-light rounded waves-effect waves-light" target="_blank">
            <i class="fab fa-github mr-2"></i>MDB GitHub
          </a>
        </li>
      </ul>

    </div>

  </div>
</nav>

<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class=""></li>
      <li data-target="#carousel-example-1z" data-slide-to="1" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2" class=""></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/77.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Become a Smart Seller With ISC</strong>
              </h1>

              <p>
                <strong>Best &amp; Free Guidence and a Product Showcase Plateform.</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most useful plateform for online local retail. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg waves-effect waves-light">Start
                Now
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url(''); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Become a Smart Seller With ISC</strong>
              </h1>

              <p>
                <strong>Best &amp; Free Guidence and a Product Showcase Plateform.</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most useful plateform for online local retail. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="#" class="btn btn-outline-white btn-lg waves-effect waves-light">Start
                Now.
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/79.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Become a Smart Seller With ISC</strong>
              </h1>

              <p>
                <strong>Best &amp; Free Guidence and a Product Showcase Plateform.</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most useful plateform for online local retail. Loved by over 500 000 users. Video and
                  written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="#" class="btn btn-outline-white btn-lg waves-effect waves-light">Start
                Now.
                <i class="fas fa-graduation-cap ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  
</body>
<script>   new WOW().init();</script>
</html>

Inventory_managment/templates/contacts.html
{% extends 'base.html' %}

{% block title %}Contact Us{% endblock title %}

{% block body %}

{% endblock body %}

Inventory_managment/templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block body1 %}

    {% endblock body1 %}
        
             {% block body2 %}
    <div class="container">
        <div class="card-deck mt-5 row">
            <div class="card col-md-3 style="width: 18rem;">
                <img src="https://source.unsplash.com/200x200/?nature" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated 3 mins ago</small>
                </div>
            </div>
            <div class="card col-md-3 style="width: 18rem;">
                <img src="https://source.unsplash.com/200x200/?nature" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated 3 mins ago</small>
                </div>
            </div>
            <div class="card col-md-3 style="width: 18rem;">
                <img src="https://source.unsplash.com/200x200/?nature" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated 3 mins ago</small>
                </div>
            </div>
        </div>
        <div class="card-deck mt-5 row">
            <div class="card col-md-3 style="width: 18rem;">
                <img src="https://source.unsplash.com/200x200/?nature" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated 3 mins ago</small>
                </div>
            </div>
            <div class="card col-md-3 style="width: 18rem;">
                <img src="https://source.unsplash.com/200x200/?nature" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
                </div>
                <div class="card-footer style="width: 18rem;">
                    <small class="text-muted">Last updated 3 mins ago</small>
                </div>
            </div>
            <div class="card col-md-3 style="width: 18rem;">
                <img src="https://source.unsplash.com/200x200/?nature" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated 3 mins ago</small>
                </div>
            </div>
        </div>
    </div>

             
             
             {% endblock body2 %}                   

Inventory_managment/templates/partners.html
{% extends 'base.html' %}

{% block title %}Our Partners{% endblock title %}

{% block body1 %}

    {% endblock body1 %}
        
             {% block body2 %}
             {% endblock body2 %} 

display_app/templates/disProducts.html
{% extends 'base.html'%}